"""
Seed script for IncidentIQ Hindsight Memory Bank.
Inserts 22 realistic historical incident post-mortems into Hindsight memory,
covering database failures, API 500s, auth timeouts, redis OOMs, payment timeouts,
high latency, high CPU, deployment failures, memory leaks, and service crashes.
"""

import os
import sys
from datetime import datetime, timezone

# Ensure backend root is on Python path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from services.hindsight_service import hindsight_service, HINDSIGHT_BANK_ID

SEED_INCIDENTS = [
    {
        "id": "INC-184",
        "title": "Database connection pool exhaustion",
        "service": "aurora-postgres-primary",
        "severity": "P1",
        "time": "2026-09-24T09:30:00Z",
        "createdAt": "2026-09-24T09:08:00Z",
        "error_logs": "FATAL: remaining connection slots are reserved for non-replication superuser connections (SQLSTATE 53300). Active pool count: 100/100. Connection timeout after 30000ms.",
        "root_cause": "Database connection pool saturated at 50 to 100 connections. Unclosed database cursor handles in transaction retry block caused connection leakage under traffic spikes.",
        "resolutionSummary": "Increased database connection pool from 50 to 100 via RDS Parameter Group; patched unclosed connection handle in commit 8f29d1c and deployed connection reaper.",
        "worked": True,
        "deployment_info": "Release v2.13.4",
        "responder": "Sarah Kim (DBA Lead)",
    },
    {
        "id": "INC-178",
        "title": "API 500 errors on ingress gateway",
        "service": "api-gateway-us-east",
        "severity": "P1",
        "time": "2026-09-21T14:15:00Z",
        "createdAt": "2026-09-21T13:50:00Z",
        "error_logs": "502 Bad Gateway / upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed_connect_error: 111",
        "root_cause": "Envoy ingress keepalive timeout was set to 60s while upstream microservices had keepalive timeout set to 60s, triggering race condition connection resets.",
        "resolutionSummary": "Increased gateway upstream keepalive timeout from 60s to 75s and executed rolling restart of Envoy router pods.",
        "worked": True,
        "deployment_info": "Traefik to Envoy gateway migration v3.1",
        "responder": "Elena Rostova (Infra SRE)",
    },
    {
        "id": "INC-172",
        "title": "Redis memory exhaustion and cache eviction storm",
        "service": "cache-redis-cluster",
        "severity": "P2",
        "time": "2026-09-17T06:30:00Z",
        "createdAt": "2026-09-17T05:50:00Z",
        "error_logs": "OOM command not allowed when used memory > 'maxmemory' (16GB). Key eviction rate spiked to 14,000 keys/sec; cache hit ratio dropped from 94% to 38%.",
        "root_cause": "Session tokens stored without TTL expiring policy during marketing push filled 16GB RAM limit, causing eviction storm that thrashed backend DB.",
        "resolutionSummary": "Applied volatile-lru eviction policy, bumped cluster memory to 32GB, and enforced mandatory 24h TTL on all session keys.",
        "worked": True,
        "deployment_info": "Promotional campaign launch v2.12",
        "responder": "Alex Chen (Lead SRE)",
    },
    {
        "id": "INC-165",
        "title": "Authentication service timeout and JWT validation failure",
        "service": "auth-service",
        "severity": "P1",
        "time": "2026-09-14T11:45:00Z",
        "createdAt": "2026-09-14T11:15:00Z",
        "error_logs": "JWKSRetrievalTimeout: Failed to fetch public key set from Auth0 endpoint within 500ms timeout threshold. Signature verification aborted.",
        "root_cause": "Stale JWKS public key cache eviction forced synchronous remote HTTP call on every request; outbound NAT gateway connection pool saturated.",
        "resolutionSummary": "Increased local JWKS memory cache TTL from 5m to 24h with stale-while-revalidate background refresh worker.",
        "worked": True,
        "deployment_info": "Security patch release v1.8.9",
        "responder": "Devin Torres (SecOps Lead)",
    },
    {
        "id": "INC-158",
        "title": "Payment gateway timeout and cascade circuit breaker trip",
        "service": "payment-service",
        "severity": "P1",
        "time": "2026-09-10T18:20:00Z",
        "createdAt": "2026-09-10T17:40:00Z",
        "error_logs": "CircuitBreakerOpenException: payment_gateway_stripe circuit breaker tripped. 54% failure rate in 60s sliding window.",
        "root_cause": "Third-party payment gateway latency spiked to 8,000ms. In-memory worker thread pool exhausted waiting for HTTP responses without socket timeout.",
        "resolutionSummary": "Configured strict 3,000ms HTTP socket timeout, increased Resilience4j circuit breaker open threshold to 70%, and enabled Redis dead-letter fallback queue.",
        "worked": True,
        "deployment_info": "Payment microservice v4.2.0",
        "responder": "Marcus Vance (Payments Lead)",
    },
    {
        "id": "INC-152",
        "title": "High API latency and thread pool starvation",
        "service": "order-service",
        "severity": "P2",
        "time": "2026-09-06T15:10:00Z",
        "createdAt": "2026-09-06T14:35:00Z",
        "error_logs": "ThreadPoolExecutor: pool size 200 reached, active threads 200, queued tasks 1850. p99 response time jumped from 45ms to 3,800ms.",
        "root_cause": "Nested synchronous gRPC call to legacy billing service without connection deadline propagation caused all worker threads to block indefinitely.",
        "resolutionSummary": "Added 800ms gRPC deadline propagation, enabled non-blocking reactive webclient, and isolated billing lookups behind dedicated thread pool.",
        "worked": True,
        "deployment_info": "Order routing update v3.5.2",
        "responder": "Priya Patel (Core Platform)",
    },
    {
        "id": "INC-144",
        "title": "Failed deployment database migration table lock",
        "service": "user-service",
        "severity": "P1",
        "time": "2026-09-02T03:45:00Z",
        "createdAt": "2026-09-02T03:10:00Z",
        "error_logs": "ERROR: canceling statement due to lock timeout. Process 4129 waits for ExclusiveLock on relation 'users_profile_tbl'. All write queries queued.",
        "root_cause": "Flyway migration script added NOT NULL column with default expression without lock timeout guard, blocking production read-write transactions.",
        "resolutionSummary": "Aborted migration transaction, set lock_timeout = '2s', added column as NULLABLE in step 1, backfilled in batches, and added constraint as VALIDATE ONLY.",
        "worked": True,
        "deployment_info": "User Schema Migration Release v2.9.0",
        "responder": "Sarah Kim (DBA Lead)",
    },
    {
        "id": "INC-137",
        "title": "PostgreSQL replica replication lag and WAL backlog",
        "service": "data-warehouse",
        "severity": "P2",
        "time": "2026-08-28T22:15:00Z",
        "createdAt": "2026-08-28T21:40:00Z",
        "error_logs": "Postgres WAL sender process killed: replication delay exceeded 14GB / 3600 seconds. Read replica lag spiked to 42 minutes.",
        "root_cause": "Long-running analytical export query on read replica acquired catalog locks that conflicted with applied WAL streaming changes.",
        "resolutionSummary": "Enabled max_standby_streaming_delay = 30s, enabled hot_standby_feedback = on, and isolated heavy analytical queries to dedicated ETL replica.",
        "worked": True,
        "deployment_info": "Nightly batch analytical exporter v1.2",
        "responder": "Alex Chen (Lead SRE)",
    },
    {
        "id": "INC-129",
        "title": "Notification service SSE connection memory leak",
        "service": "notification-service",
        "severity": "P2",
        "time": "2026-08-24T16:00:00Z",
        "createdAt": "2026-08-24T15:20:00Z",
        "error_logs": "FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory. RSS memory grew from 250MB to 1.8GB.",
        "root_cause": "Server-Sent Events connection cleanup handler failed to unbind client event listeners on unexpected TCP close, leaking connection buffers in memory.",
        "resolutionSummary": "Rewrote SSE disconnect lifecycle handler with explicit listener removal, added heartbeat ping-pong, and capped max heap to 2GB with container auto-recycle.",
        "worked": True,
        "deployment_info": "Realtime notification update v2.4.1",
        "responder": "Elena Rostova (Infra SRE)",
    },
    {
        "id": "INC-121",
        "title": "Async worker crash loop from unhandled SIGTERM signal",
        "service": "async-worker",
        "severity": "P2",
        "time": "2026-08-20T08:30:00Z",
        "createdAt": "2026-08-20T08:00:00Z",
        "error_logs": "K8s Pod OOMKilled/CrashLoopBackOff: exit code 137. 24 unacknowledged messages re-queued onto RabbitMQ dead-letter exchange concurrently.",
        "root_cause": "Kubernetes node preemption sent SIGTERM to Celery workers; shutdown handler did not wait for in-flight jobs to complete before terminating database session.",
        "resolutionSummary": "Configured terminationGracePeriodSeconds to 60s in Pod spec and added graceful SIGTERM drain handler with Celery warm shutdown.",
        "worked": True,
        "deployment_info": "Node autoscaler upgrade v1.28",
        "responder": "Alex Chen (Lead SRE)",
    },
    {
        "id": "INC-115",
        "title": "PostgreSQL deadlock during batch invoice generation",
        "service": "billing-db",
        "severity": "P1",
        "time": "2026-08-16T10:15:00Z",
        "createdAt": "2026-08-16T09:45:00Z",
        "error_logs": "ERROR: deadlock detected. Process 14892 waits for ShareLock on transaction 8921827; Process 14893 waits for ExclusiveLock on tuple (48, 12).",
        "root_cause": "Concurrent billing cron jobs acquired row locks on customer invoices in reverse primary key order, triggering deterministic database deadlocks.",
        "resolutionSummary": "Sorted customer invoice IDs prior to acquiring SELECT FOR UPDATE row locks, eliminating lock inversion order.",
        "worked": True,
        "deployment_info": "Monthly subscription billing cycle v2.10",
        "responder": "Sarah Kim (DBA Lead)",
    },
    {
        "id": "INC-110",
        "title": "High CPU throttling on Checkout microservice",
        "service": "checkout-service",
        "severity": "P2",
        "time": "2026-08-12T13:40:00Z",
        "createdAt": "2026-08-12T13:05:00Z",
        "error_logs": "cgroup CPU throttling exceeded 84% on checkout-worker pods. p99 response time spiked from 25ms to 2,400ms.",
        "root_cause": "Regex catastrophic backtracking in promo code validation routine caused exponential CPU evaluation on strings with repeated hyphens.",
        "resolutionSummary": "Rewrote promo code regex validator using linear RE2 engine without backtracking and increased Kubernetes CPU limits from 1.0 to 2.5 cores.",
        "worked": True,
        "deployment_info": "Summer promotion release v3.4.1",
        "responder": "Priya Patel (Core Platform)",
    },
    {
        "id": "INC-105",
        "title": "Kafka consumer group rebalance storm",
        "service": "event-streaming-kafka",
        "severity": "P1",
        "time": "2026-08-08T19:20:00Z",
        "createdAt": "2026-08-08T18:50:00Z",
        "error_logs": "CommitFailedException: Offset commit cannot be completed since the group has already rebalanced. max.poll.interval.ms exceeded.",
        "root_cause": "Heavy image processing task inside Kafka message handler exceeded 300,000ms poll interval, causing coordinator to evict consumer and trigger perpetual rebalance.",
        "resolutionSummary": "Decoupled image processing onto asynchronous worker thread pool and increased max.poll.interval.ms from 5m to 15m.",
        "worked": True,
        "deployment_info": "Media pipeline upgrade v1.9.0",
        "responder": "Elena Rostova (Infra SRE)",
    },
    {
        "id": "INC-098",
        "title": "Elasticsearch cluster yellow status and JVM memory pressure",
        "service": "search-cluster",
        "severity": "P2",
        "time": "2026-08-04T12:00:00Z",
        "createdAt": "2026-08-04T11:25:00Z",
        "error_logs": "CircuitBreakingException: [parent] Data too large, data for [<transport_request>] would be [31849182740/29.6gb], which is larger than the limit of [30601641984/28.5gb].",
        "root_cause": "Unbounded wildcard terms aggregation over catalog search logs filled JVM fielddata cache, tripping the circuit breaker and stalling index queries.",
        "resolutionSummary": "Cleared fielddata cache, disabled wildcard aggregations on non-keyword fields, and added indices.fielddata.cache.size: 20% limit.",
        "worked": True,
        "deployment_info": "Search telemetry expansion v2.6",
        "responder": "Marcus Vance (Search Team)",
    },
    {
        "id": "INC-092",
        "title": "Core DNS resolution timeout on AWS NAT Gateway",
        "service": "core-network",
        "severity": "P1",
        "time": "2026-07-31T07:15:00Z",
        "createdAt": "2026-07-31T06:45:00Z",
        "error_logs": "dial tcp: lookup api.stripe.com on 10.0.0.2:53: i/o timeout. 5-second DNS resolution latency spikes on outbound HTTPS calls.",
        "root_cause": "Node-local CoreDNS daemonset crashed on 3 worker nodes due to conntrack table exhaustion on Linux kernel netfilter.",
        "resolutionSummary": "Increased nf_conntrack_max from 262144 to 1048576 via sysctl and deployed NodeLocal DNSCache daemon to bypass conntrack for internal lookups.",
        "worked": True,
        "deployment_info": "Kubernetes 1.28 cluster patch",
        "responder": "Elena Rostova (Infra SRE)",
    },
    {
        "id": "INC-087",
        "title": "S3 multipart upload file descriptor leak",
        "service": "asset-storage-svc",
        "severity": "P2",
        "time": "2026-07-27T17:30:00Z",
        "createdAt": "2026-07-27T16:55:00Z",
        "error_logs": "EMFILE: too many open files. Process exceeded ulimit of 1024 open file descriptors. New incoming upload requests refused with 500.",
        "root_cause": "Temporary upload staging chunks were opened with fs.createReadStream without listening to error event, leaving file descriptors open on client abort.",
        "resolutionSummary": "Used stream.pipeline() with auto-close semantics, raised container nofile ulimit to 65535, and scheduled automated orphaned chunk cleanup cron.",
        "worked": True,
        "deployment_info": "Asset upload service v1.6.3",
        "responder": "Devin Torres (SecOps Lead)",
    },
    {
        "id": "INC-081",
        "title": "Ingress edge SSL intermediate certificate expiration",
        "service": "k8s-ingress-edge",
        "severity": "P1",
        "time": "2026-07-23T04:10:00Z",
        "createdAt": "2026-07-23T03:50:00Z",
        "error_logs": "SEC_ERROR_UNKNOWN_ISSUER / Peer's Certificate issuer is not recognized. Edge SSL handshake dropped for 100% of non-cached mobile clients.",
        "root_cause": "cert-manager secret renewed leaf certificate but omitted full intermediate CA chain bundle in TLS Kubernetes secret.",
        "resolutionSummary": "Re-issued certificate using cert-manager with fullchain.pem including Sectigo intermediate bundle, and restarted edge Traefik pods.",
        "worked": True,
        "deployment_info": "Automated certificate rotation cycle",
        "responder": "Alex Chen (Lead SRE)",
    },
    {
        "id": "INC-076",
        "title": "Rate limiting token bucket Redis desync",
        "service": "rate-limiter-service",
        "severity": "P2",
        "time": "2026-07-19T21:40:00Z",
        "createdAt": "2026-07-19T21:10:00Z",
        "error_logs": "HTTP 429 Too Many Requests returned for valid internal API consumers. Token bucket counter evaluated negative balance.",
        "root_cause": "Non-atomic GET then SET operations in rate limiter allowed concurrent worker race condition to overwrite bucket timestamp with future clock drift.",
        "resolutionSummary": "Migrated rate-limiting logic to atomic Redis Lua script executing token replenishment and deduction in a single transaction.",
        "worked": True,
        "deployment_info": "API security hardening v2.3.0",
        "responder": "Priya Patel (Core Platform)",
    },
    {
        "id": "INC-071",
        "title": "Node.js WebSocket gateway memory leak during reconnect storms",
        "service": "realtime-gateway",
        "severity": "P1",
        "time": "2026-07-15T14:50:00Z",
        "createdAt": "2026-07-15T14:15:00Z",
        "error_logs": "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory. 14 gateway pods restarted simultaneously.",
        "root_cause": "Client reconnect storm queued offline messages in an unbounded array per socket without backpressure limits.",
        "resolutionSummary": "Implemented bounded circular ring buffer (max 100 queued messages per client) and applied exponential reconnect jitter on frontend SDK.",
        "worked": True,
        "deployment_info": "Realtime chat release v3.0.1",
        "responder": "Elena Rostova (Infra SRE)",
    },
    {
        "id": "INC-065",
        "title": "Failed canary deployment route saturation",
        "service": "inventory-service",
        "severity": "P2",
        "time": "2026-07-11T10:30:00Z",
        "createdAt": "2026-07-11T10:00:00Z",
        "error_logs": "Argo Rollouts canary weight 10% overwhelmed single canary replica pod. CPU 100%, 503 Service Unavailable for 12% of traffic.",
        "root_cause": "Canary step configuration increased traffic weight before horizontal pod autoscaler (HPA) had scaled minimum replicas from 1 to 4.",
        "resolutionSummary": "Added minimum replica constraint (minReplicas: 4) before canary traffic shift and configured automated rollback on 5xx error rate > 2%.",
        "worked": True,
        "deployment_info": "Canary Rollout v2.1.0",
        "responder": "Alex Chen (Lead SRE)",
    },
    {
        "id": "INC-058",
        "title": "Unindexed foreign key constraint query spillover",
        "service": "reporting-db",
        "severity": "P2",
        "time": "2026-07-07T16:20:00Z",
        "createdAt": "2026-07-07T15:45:00Z",
        "error_logs": "Seq Scan on order_items (cost=0.00..1849182.20 rows=48210920). Query execution time: 142 seconds, saturating IOPS limit on EBS gp3 volume.",
        "root_cause": "Deletion cascade on parent orders table triggered full sequential table scan on 48M row child table lacking index on order_id column.",
        "resolutionSummary": "Created concurrent index CREATE INDEX CONCURRENTLY idx_order_items_order_id ON order_items(order_id); query time dropped to 2ms.",
        "worked": True,
        "deployment_info": "Reporting DB cleanup job",
        "responder": "Sarah Kim (DBA Lead)",
    },
    {
        "id": "INC-052",
        "title": "gRPC deadline propagation cascade failure",
        "service": "recommendation-engine",
        "severity": "P1",
        "time": "2026-07-03T11:00:00Z",
        "createdAt": "2026-07-03T10:30:00Z",
        "error_logs": "rpc error: code = DeadlineExceeded desc = context deadline exceeded. 100% cascade timeout across all upstream recommendation widgets.",
        "root_cause": "Upstream service had 1000ms timeout while downstream vector search had 1200ms timeout. Upstream cancelled request while downstream kept computing wasted vector queries.",
        "resolutionSummary": "Propagated gRPC context deadline throughout all RPC child contexts, enabling immediate cooperative cancellation when caller aborts.",
        "worked": True,
        "deployment_info": "Recommendation v1.4.0",
        "responder": "Marcus Vance (Payments Lead)",
    },
]


def seed_hindsight_memories():
    print(f"Connecting to Hindsight memory service at {hindsight_service.base_url}...")
    if not hindsight_service.is_available():
        print(f"Error: Hindsight service at {hindsight_service.base_url} is not reachable.")
        sys.exit(1)

    print(f"Configuring IncidentIQ memory bank '{HINDSIGHT_BANK_ID}'...")
    hindsight_service.ensure_bank_exists()

    print(f"\nRetaining {len(SEED_INCIDENTS)} realistic historical incidents into Hindsight...\n")
    success_count = 0

    for inc in SEED_INCIDENTS:
        result = hindsight_service.retain_incident(inc)
        if result.get("success"):
            print(f"[OK] {inc['id']}: {inc['title']} -> Retained in bank '{HINDSIGHT_BANK_ID}'")
            success_count += 1
        else:
            print(f"[FAIL] {inc['id']}: {result.get('error')}")

    print(f"\nSeeding complete: {success_count}/{len(SEED_INCIDENTS)} historical incidents retained in Hindsight.")


if __name__ == "__main__":
    seed_hindsight_memories()
